# Generated by Django 3.2.12 on 2022-03-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_image_app', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
